version: '3.8'

services:
  tile-server:
    image: overv/openstreetmap-tile-server
    container_name: osm_tile_server
    ports:
      - "8080:80"
    volumes:
      - osm-data:/data/database
      - tile-cache:/var/lib/mod_tile # Persist the cache
    environment:
      - ALLOW_CORS=1 # Enable CORS
    command: run
    restart: unless-stopped

volumes:
  osm-data:
    external: true
  tile-cache:
